data:
  path: /data
  target_column: 'toxic'
  test_size: 0.2


logistic_regression:
  C: 1.0
  max_iter: 1000
  random_state: 42
  class_weight: 'balanced'

tfidf:
  max_features: 5000
  stop_words: 'russian'

model:
  model_name: 'cointegrated/rubert-tiny2'
  num_classes: 2

training:
  seed: 42
  batch_size: 32
  num_epochs: 3
  learning_rate: 2e-5