data:
  path: "data/processed/cleaned_dataset.csv"
  target_column: "toxic"
  text_column: "comment"
  test_size: 0.2

model:
  model_name: "cointegrated/rubert-tiny2"
  num_classes: 2

mymodelv2_params:
  embedding_dim: 256
  num_heads: 2
  num_layers: 2
  num_classes: 2  
  max_seq_length: 512

training:
  seed: 42
  batch_size: 32
  bert_epochs: 5
  mymodel_epochs: 7

  bert_lr: 2e-5      
  mymodel_lr: 3e-4   